FROM python:3.7-slim
RUN mkdir /app
ADD integration/airflow/setup.py /app
ADD integration/airflow/README.md /app
COPY client/python /tmp/openlineage-client-python
COPY integration/common /tmp/openlineage-integration-common
COPY integration/dbt /tmp/openlineage-integration-dbt
RUN cd /tmp/openlineage-client-python && pip wheel --no-deps --wheel-dir=/tmp/openlineage-client-python/wheel .
RUN cd /tmp/openlineage-integration-common && pip wheel --no-deps --wheel-dir=/tmp/openlineage-integration-common/wheel .
RUN cd /tmp/openlineage-integration-dbt && pip wheel --no-deps --wheel-dir=/tmp/openlineage-integration-dbt/wheel .
COPY integration/airflow/openlineage /app/openlineage
WORKDIR /app
RUN ls -halt /tmp/openlineage-client-python/wheel
RUN pip wheel --no-deps --wheel-dir=/app/wheel -e /tmp/openlineage-client-python .[tests]
RUN pip wheel --no-deps --wheel-dir=/app/wheel -e /tmp/openlineage-integration-common .[tests]
RUN pip wheel --no-deps --wheel-dir=/app/wheel -e /tmp/openlineage-integration-dbt .[tests]
RUN cp -R /app/wheel /whl
RUN cp /tmp/openlineage-integration-common/wheel/openlineage_integration_common* /whl
